# Generated by Django 2.2.24 on 2024-03-27 13:09

from django.db import migrations

def new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building = Flat.objects.all().filter(construction_year__gte=2015)
    new_building.update(new_building='True')
    old_building = Flat.objects.all().filter(construction_year__lt=2015)
    old_building.update(new_building='False')

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20240326_1341'),
    ]

    operations = [
        migrations.RunPython(new_building),
    ]
