# Generated by Django 2.2.24 on 2024-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20240327_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(max_length=200, on_delete='ФИО владельца', related_name='flats', to='property.Flat')),
            ],
        ),
    ]
