# Generated by Django 2.2.24 on 2024-03-27 20:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(blank=True, related_name='flats', to='property.Flat'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
