# Generated by Django 2.2.24 on 2024-03-28 12:24

from django.db import migrations


def add_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner, owner_pure_phone=flat.owner_pure_phone,
                                    owners_phonenumber=flat.owners_phonenumber)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20240327_2327'),
    ]

    operations = [
        migrations.RunPython(add_owners),
    ]
