# Generated by Django 2.2.24 on 2024-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20240328_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owned_by',
            field=models.ManyToManyField(blank=True, to='property.Owner', verbose_name='Принадлежит'),
        ),
    ]
