# Generated by Django 2.2.24 on 2024-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_flat_owned_by'),
    ]

    operations = [

    ]
