# Generated by Django 2.2.24 on 2024-03-28 13:05

from django.db import migrations

def connect_owners_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        flat_owned = flat.flats.all()
        flat.owned_by.set(flat_owned)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_flat_owned_by'),
    ]

    operations = [
        migrations.RunPython(connect_owners_flat),
    ]
