# Generated by Django 2.2.24 on 2024-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20240402_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(blank=True, related_name='own_flats', to='property.Flat'),
        ),
    ]
