# Generated by Django 2.2.24 on 2024-04-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_auto_20240402_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flats',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
    ]
